import{configureStore} from "@reduxjs/toolkit";
import {apiSlice} from "@/app/store/api/apiSlice";
const store =configureStore({
    reducer:{
        [apiSlice.reducerPath]: apiSlice.reducer,
        // automatically generated by the api slice
        // redux erPath is the name of the slice
        // store cha

    },
    middleware: (getDefaultMiddleware) => {
        return getDefaultMiddleware().concat(apiSlice.middleware);
    },
    devTools: true,
});
export default store;