spring:
  application:
    name: product-service
  profiles:
    active: native
  config:
    import: optional:configserver:http://localhost:8888

---
spring.config.activate.on-profile: docker

server.port: 8080