spring:
  config:
    import: optional:configserver:http://${CONFIG_SERVER_URL:localhost}:8888
  profiles:
    active: native
  application:
    name: eureka-server
  cloud.config:
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 20
app:
  eureka-username: u
  eureka-password: p