server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aggregator-microservice
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect