spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://34.87.36.136:1804/schedule_service
    username: spring
    password: spring!@#
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080

